In [1]:
import sys
sys.path.append("../src")

from data_loader import load_raw_data, time_based_split
from features import add_velocity_features, add_amount_deviation_features

data = load_raw_data()
train_df, test_df = time_based_split(data)
del data

Train range: 86400 to 12192842
Test range:  12192900 to 15811131
Train shape: (472432, 434), Test shape: (118108, 434)
Train fraud rate: 3.51%
Test fraud rate:  3.44%

In [2]:
train_df = add_velocity_features(train_df)
train_df = add_amount_deviation_features(train_df)

train_df[["TransactionID", "card1", "TransactionAmt", 
          "card1_txn_count_1d", "card1_txn_amt_sum_1d",
          "amt_deviation_from_avg"]].head(20)

,TransactionID,card1,TransactionAmt,card1_txn_count_1d,card1_txn_amt_sum_1d,amt_deviation_from_avg
0,2987000,13926,68.500000,0.0,0.0,0.0
1,2987001,2755,29.000000,0.0,0.0,0.0
2,2987002,4663,59.000000,0.0,0.0,0.0
3,2987003,18132,50.000000,0.0,0.0,0.0
4,2987004,4497,50.000000,0.0,0.0,0.0
5,2987005,5937,49.000000,0.0,0.0,0.0
6,2987006,12308,159.000000,0.0,0.0,0.0
7,2987007,12695,422.500000,0.0,0.0,0.0
8,2987008,2803,15.000000,0.0,0.0,0.0
9,2987009,17399,117.000000,0.0,0.0,0.0
10,2987010,16496,75.887001,0.0,0.0,0.0
11,2987011,4461,16.495001,0.0,0.0,0.0
12,2987012,3786,50.000000,0.0,0.0,0.0
13,2987013,12866,40.000000,0.0,0.0,0.0
14,2987014,11839,10.500000,0.0,0.0,0.0
15,2987015,7055,57.950001,0.0,0.0,0.0
16,2987016,1790,30.000000,0.0,0.0,0.0
17,2987017,11492,100.000000,0.0,0.0,0.0
18,2987018,4663,47.950001,1.0,59.0,0.0
19,2987019,7005,186.000000,0.0,0.0,0.0

In [3]:
train_df[train_df["card1_txn_count_1d"] > 0][
    ["TransactionID", "card1", "TransactionAmt", "card1_txn_count_1d", 
     "card1_txn_amt_sum_1d", "amt_deviation_from_avg"]
].head(10)

,TransactionID,card1,TransactionAmt,card1_txn_count_1d,card1_txn_amt_sum_1d,amt_deviation_from_avg
18,2987018,4663,47.950001,1.0,59.000000,0.000000
51,2987051,7835,226.000000,1.0,200.000000,0.000000
57,2987057,11839,50.000000,1.0,10.500000,0.000000
61,2987061,12544,58.950001,1.0,49.000000,0.000000
62,2987062,18132,200.000000,1.0,50.000000,0.000000
69,2987069,12866,20.000000,1.0,40.000000,0.000000
73,2987073,1955,554.000000,1.0,500.000000,0.000000
74,2987074,15885,27.792999,1.0,42.293999,0.000000
75,2987075,4806,68.500000,1.0,77.000000,0.000000
76,2987076,18132,36.950001,2.0,250.000000,-0.830143